/**
 * src/services/ai/aiService.js
 * Exists to synthesize speech and visual metrics into a comprehensive feedback report.
 * Supports both OpenAI (Chat Completion) and Gemini (Generative Model).
 * Implements a high-fidelity local feedback synthesizer fallback when API keys are absent.
 */

const { OpenAI } = require("openai");
const { GoogleGenAI } = require("@google/generative-ai");
const logger = require("../../config/logger");
const { formatSecondsToMMSS } = require("../../utils/helpers");

/**
 * Main function to generate the coaching report using LLM or local fallback.
 * @param {object} inputData Combined speech and vision metrics
 * @returns {Promise<object>} Final structured report JSON
 */
const generateCoachingReport = async (inputData) => {
  const provider = (process.env.AI_PROVIDER || "openai").toLowerCase();
  const openaiKey = process.env.OPENAI_API_KEY;
  const geminiKey = process.env.GEMINI_API_KEY;

  // Check if we can use an actual API
  const canUseOpenAI = provider === "openai" && openaiKey && !openaiKey.startsWith("your_");
  const canUseGemini = provider === "gemini" && geminiKey && !geminiKey.startsWith("your_");

  logger.info(`Generating coaching report using provider: ${provider} (Real API: ${canUseOpenAI || canUseGemini})`);

  const prompt = constructPrompt(inputData);

  let rawResponse = null;

  if (canUseOpenAI) {
    rawResponse = await callOpenAI(openaiKey, prompt);
  } else if (canUseGemini) {
    rawResponse = await callGemini(geminiKey, prompt);
  }

  if (rawResponse) {
    try {
      // Clean up markdown block wrapping if returned
      const cleanJsonStr = rawResponse
        .replace(/```json/g, "")
        .replace(/```/g, "")
        .trim();
      const parsedReport = JSON.parse(cleanJsonStr);
      logger.success("Coaching report successfully generated by LLM API.");
      return parsedReport;
    } catch (parseErr) {
      logger.error("LLM returned invalid JSON. Falling back to local synthesizer.", parseErr);
    }
  }

  // Fallback to local rule-based coaching generator
  return compileLocalCoachingReport(inputData);
};

/**
 * Standardized system prompt to instruct the LLM on output schema.
 */
const constructPrompt = (data) => {
  return `
You are an expert Speech Coach, Body Language Expert, and Communications Consultant.
You will analyze the following structured data from a video of a user speaking:

### TRANSCRIPT
"${data.transcriptText}"

### SPEECH METRICS
- Speaking Speed: ${data.speechMetrics.speakingSpeed} Words Per Minute (WPM) (Ideal: 120-160 WPM)
- Vocabulary Diversity Index: ${data.speechMetrics.vocabularyDiversity} (Type-Token Ratio, 0 to 1)
- Average Sentence Length: ${data.speechMetrics.averageSentenceLength} words
- Filler Words Count: ${data.speechMetrics.fillerWords.length} (Filler words found: ${JSON.stringify(data.speechMetrics.fillerWords.map(f => f.word))})
- Repeated Words Count: ${data.speechMetrics.repeatedWords.length}
- Pauses Count: ${data.speechMetrics.pauses.length} (Pauses details: ${JSON.stringify(data.speechMetrics.pauses)})

### COMPUTER VISION METRICS (MediaPipe)
- Overall Eye Contact Percentage: ${data.visionSummary.eyeContactPercent}%
- Slouching Frames Percentage: ${data.visionSummary.slouchingPercent}%
- Good Posture Frames Percentage: ${data.visionSummary.goodPosturePercent}%
- Hand Movement Gestures Percentage: ${data.visionSummary.handsVisiblePercent}%
- Smiling Frames Percentage: ${data.visionSummary.smilingPercent}%
- Blink Count: ${data.visionSummary.blinkCount}

### DETECTED INSTANCES WITH TIMESTAMPS
- Filler Words: ${JSON.stringify(data.speechMetrics.fillerWords.map(f => ({ time: f.formattedStart, word: f.word })))}
- Posture issues (e.g., Slouching): ${JSON.stringify(data.detectedVisionIssues.posture)}
- Eye contact issues (looks away): ${JSON.stringify(data.detectedVisionIssues.eyeContact)}

---

Generate a comprehensive report strictly in JSON format. Do not write any conversational intro or outro. Output only the JSON.

JSON Structure:
{
  "overallScore": <Number between 0 and 100>,
  "confidenceScore": <Number between 0 and 100>,
  "grammarScore": <Number between 0 and 100>,
  "bodyLanguageScore": <Number between 0 and 100>,
  "eyeContactScore": <Number between 0 and 100>,
  "postureScore": <Number between 0 and 100>,
  "gestureScore": <Number between 0 and 100>,
  "communicationScore": <Number between 0 and 100>,
  "vocabularyScore": <Number between 0 and 100>,
  "speakingSpeed": <Number (speaking WPM)>,
  "summary": "<A detailed, professional executive summary of the user's speaking session>",
  "strengths": [
    "<Strength 1>",
    "<Strength 2>",
    "<Strength 3>"
  ],
  "weaknesses": [
    "<Weakness 1>",
    "<Weakness 2>",
    "<Weakness 3>"
  ],
  "timeline": [
    {
      "startTime": "MM:SS",
      "endTime": "MM:SS",
      "category": "Speech" | "Eye Contact" | "Posture" | "Gesture",
      "issue": "<Short description of the problem>",
      "suggestion": "<Actionable advice on how to improve this specific instance>"
    }
  ]
}

For the "timeline", use the timestamped events provided in the data. Add practical suggestions. 
Make sure the score values correlate logically with the metrics (e.g. high filler counts should reduce confidenceScore/communicationScore, high slouching should reduce postureScore/bodyLanguageScore).
`;
};

/**
 * Calls OpenAI Chat Completions API.
 */
const callOpenAI = async (apiKey, prompt) => {
  try {
    const openai = new OpenAI({ apiKey });
    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: "You are a JSON-only API. You output valid JSON conforming to the requested schema. No explanations, no markdown blocks." },
        { role: "user", content: prompt }
      ],
      temperature: 0.2
    });
    return completion.choices[0].message.content;
  } catch (error) {
    logger.error("OpenAI chat completion failed:", error);
    return null;
  }
};

/**
 * Calls Google Gemini API.
 */
const callGemini = async (apiKey, prompt) => {
  try {
    // gemini-2.5-flash is standard, fast, and powerful
    const genAI = new GoogleGenAI({ apiKey });
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const result = await model.generateContent(prompt);
    return result.response.text();
  } catch (error) {
    logger.error("Gemini content generation failed:", error);
    return null;
  }
};

/**
 * Local rule-based coaching feedback compiler.
 * Programmatically builds structured reports and feedback timelines from actual data.
 */
const compileLocalCoachingReport = (data) => {
  logger.info("Compiling report locally using rule-based algorithms...");

  const wpm = data.speechMetrics.speakingSpeed;
  const fillers = data.speechMetrics.fillerWords;
  const pauses = data.speechMetrics.pauses;
  const eyeContactPct = data.visionSummary.eyeContactPercent;
  const posturePct = data.visionSummary.goodPosturePercent;
  const handsPct = data.visionSummary.handsVisiblePercent;

  // 1. Calculate Scores programmatically
  const speakingSpeedScore = wpm >= 120 && wpm <= 160 ? 95 : (wpm < 120 ? Math.max(50, wpm * 0.75) : Math.max(50, 100 - (wpm - 160) * 0.8));
  const eyeContactScore = eyeContactPct;
  const postureScore = posturePct;
  const gestureScore = Math.min(100, handsPct + 20); // offset because constant gestures are not necessary
  const vocabularyScore = Math.round(data.speechMetrics.vocabularyDiversity * 100);
  
  let confidenceScore = data.speechMetrics.confidenceScore;
  confidenceScore = Math.round((confidenceScore + eyeContactPct + posturePct) / 3);

  const grammarScore = wpm > 0 ? 90 : 0; // baseline grammar score
  const communicationScore = Math.round((speakingSpeedScore + vocabularyScore + confidenceScore) / 3);
  
  const bodyLanguageScore = Math.round((eyeContactScore + postureScore + gestureScore) / 3);
  const overallScore = Math.round((communicationScore + bodyLanguageScore + grammarScore) / 3);

  // 2. Synthesize strengths & weaknesses
  const strengths = [];
  const weaknesses = [];

  if (wpm >= 120 && wpm <= 160) {
    strengths.push("Excellent speaking speed. Your rate of speech sits in the ideal conversational window (120-160 WPM), making it easy to follow.");
  } else if (wpm > 160) {
    weaknesses.push("Fast pace. You are speaking at a quick tempo which may make it difficult for listeners to absorb complex arguments.");
  } else {
    weaknesses.push("Slow pace. Speaking slowly can cause listener attention to drift. Try to inject more energy into your delivery.");
  }

  if (fillers.length <= 2) {
    strengths.push("Highly fluent articulation. You used very few filler words, which adds professionalism to your delivery.");
  } else {
    weaknesses.push(`High filler usage. You used ${fillers.length} filler words. Pausing intentionally can help replace filler terms.`);
  }

  if (eyeContactPct >= 80) {
    strengths.push("Strong eye contact. You consistently look at the camera, projecting confidence and connection to the audience.");
  } else {
    weaknesses.push("Inconsistent eye contact. Looking away or gazing down weakens message authority. Focus on the camera lens.");
  }

  if (posturePct >= 80) {
    strengths.push("Assertive posture. By keeping your shoulders aligned and avoiding slouching, you display leadership poise.");
  } else {
    weaknesses.push("Tendency to slouch. Slouching projects low energy. Focus on opening up your shoulders and standing/sitting tall.");
  }

  if (handsPct >= 40) {
    strengths.push("Active hand gestures. Dynamic gesticulation helps emphasize core arguments and makes you appear warmer.");
  } else {
    weaknesses.push("Under-utilized gestures. Keeping hands static can make your delivery appear rigid. Try using hand shapes to emphasize numbers or size.");
  }

  // 3. Compile timeline feedback objects from exact occurrences
  const timeline = [];

  // Speech timeline (fillers)
  fillers.forEach((f) => {
    timeline.push({
      startTime: f.formattedStart,
      endTime: f.formattedEnd,
      category: "Speech",
      issue: `Used filler word "${f.word}"`,
      suggestion: "Pause momentarily rather than filling the silence with unnecessary vocalized pauses."
    });
  });

  // Speech timeline (long pauses)
  pauses.forEach((p) => {
    timeline.push({
      startTime: p.formattedStart,
      endTime: p.formattedEnd,
      category: "Speech",
      issue: `Long pause of ${p.duration}s`,
      suggestion: "A pause is good, but if it exceeds 2 seconds without slides, it can feel awkward. Bridge transitions smoothly."
    });
  });

  // Vision timeline (looks away / poor eye contact)
  data.detectedVisionIssues.eyeContact.forEach((ec) => {
    timeline.push({
      startTime: formatSecondsToMMSS(ec.start),
      endTime: formatSecondsToMMSS(ec.end),
      category: "Eye Contact",
      issue: "Looking away from the camera",
      suggestion: "Maintain direct gaze with the camera to command authority and build listener rapport."
    });
  });

  // Vision timeline (slouching)
  data.detectedVisionIssues.posture.forEach((ps) => {
    timeline.push({
      startTime: formatSecondsToMMSS(ps.start),
      endTime: formatSecondsToMMSS(ps.end),
      category: "Posture",
      issue: "Slouching posture detected",
      suggestion: "Sit or stand up straight. Pull your shoulders back to project a confident, professional presence."
    });
  });

  // Sort timeline by start time
  timeline.sort((a, b) => {
    const timeA = a.startTime.split(":").map(Number);
    const timeB = b.startTime.split(":").map(Number);
    return (timeA[0] * 60 + timeA[1]) - (timeB[0] * 60 + timeB[1]);
  });

  const summary = `You delivered a session at ${wpm} WPM. Your posture was good ${posturePct}% of the time, and eye contact was maintained ${eyeContactPct}% of the session. You showed ${strengths.length} key strengths, and we identified areas for improvement, especially regarding filler words and body stance. Use the interactive timeline below to practice specific segments.`;

  return {
    overallScore,
    confidenceScore,
    grammarScore,
    bodyLanguageScore,
    eyeContactScore,
    postureScore,
    gestureScore,
    communicationScore,
    vocabularyScore,
    speakingSpeed: wpm,
    summary,
    strengths: strengths.slice(0, 3), // return max 3
    weaknesses: weaknesses.slice(0, 3), // return max 3
    timeline
  };
};

module.exports = {
  generateCoachingReport
};
